.TH MOMUMA 1 "09/05/2023"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
momuma \- Mono's Music Manager
.SH SYNOPSIS
.B momuma
.RI [ OPTIONS ]
.SH DESCRIPTION
This manual page documents briefly the
.B Momuma
audio manager and player.

.SH OPTIONS
.B Momuma
follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
For a precise description of options, please use "momuma \-\-help".

.PP
.SH AUTHOR
This manual page was written by Monochrome Sauce <https://github.com/Monochrome-Sauce>, for the Debian GNU/Linux system (but may be used by others).
